#title in header
title: "Welcome"

#main info
#owner
owner: "Rahul Gurung"
email: gurrrung@gmail.com
info: "Software Engineer @Walmart"
#description
desc: ""

#menu
menu:
  Talks: /talks
  Projects: /projects
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/gurrrung
linkedin: https://www.linkedin.com/in/gurrrung/
twitter: https://twitter.com/gurrrung
instagram: https://www.instagram.com/gurrrrung/
stackoverflow: https://stackoverflow.com/users/9514156/r-gurung

# Misc
nanobar: /js/nanobar.min.js
switch_light: ‚òÄÔ∏è
switch_dark: üåë

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: rahulgurung
